[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
grid = "rdiVoU6KomhXBDMLi6UXVHvmjEUtKqb5iDCWChxMzZ7"
players = "5Xz6iiE2FZdpqrvCKbGqDajNYt1tP8cRGXrq3THSFo1q"
join-game = "2umhnxiCtmg5KTn4L9BLo24uLjb74gAh4tmpMLRKYndN"
play = "DyUy1naq1kb3r7HYBrTf7YhnGMJ5k5NqS3Mhk65GfSih"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*", "programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
