[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
grid = "9EoKMqQqrgRAxVED34q17e466RKme5sTUkuCqUGH4bij"
join-game = "7TsTc97MB21EKbh2RetcWsGWRJ4xuMkPKKD4DcMJ2Sms"
play = "EFLfG5icLgcUYwuSnuScoYptcrgh8WYLHx33M4wvTPFv"
players = "HLzXXTbMUjemRSQr5LHjtZgBvqyieuhY8wE29xYzhZSX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs-ecs/components/*", "programs-ecs/systems/*"]

[scripts]
test = "sleep 5 && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "WorLD15A7CrDwLcLy4fRqtaTb9fbd8o8iqiEMUDse2n"
program = "tests/fixtures/world.so"
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://rpc.magicblock.app/devnet/"
ledger = ".bolt/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "EHLkWwAT9oebVv9ht3mtqrvHhRVMKrt54tF3MfHTey2K"
filename = "tests/fixtures/registry.json"
